name: upower
version: 0.0.0-dev.2

description:
  Provides a client to connect to UPower - the service that does power management on Linux.

homepage: https://github.com/canonical/upower.dart

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  dbus: ^0.1.1

dev_dependencies:
  pedantic: ^1.9.0
